### PR TITLE
Add new driver for vl53l0x

### PR DESCRIPTION
**Pull request by afp316**
@brentru @ladyada 
This was more straightforward than the vl53l4cd ToF sensor given there is a dedicated Adafruit library for vl53l0x; it was pretty much copy/paste following the MCP9808 guidelines (https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component-driver)

As always, your support is so appreciated and please let me know where I go wrong so that improvements can be made on my part. Thank you!! :)

### CODE REVIEW

**Comment by brentru** [comment]
@afp316 You also need to create another pull request within https://github.com/adafruit/Wippersnapper_Components for the V53l0X sensor. 

Let me know when the component definition has been created for this sensor and I'll take a look!

**Comment by afp316** [comment]
> Does this match up with the [adafruit/Wippersnapper_Components#57](https://github.com/adafruit/Wippersnapper_Components/pull/57) component?

Yes, it does. Thanks!

**Comment by afp316** [comment]
@brentru The latest PR replaces an instance of `proximityEvent->proximity` with `proximityEvent->data[0]` as well as two instances of `event.proximity` with `event.data[0]` per your guidance in PR #289

**Comment by brentru** [comment]
@afp316  The driver looks much better and compiles, thanks for the work! Next, please format it using clang-format (we have a guide on this here: https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format) as its failing the clang-format test step (https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/runs/7682729616?check_suite_focus=true).

**Comment by afp316** [comment]
Copy that, thanks.
I'll check that out this evening...new to clang formatting.

**Comment by brentru** [comment]
Hi @afp316  - this pull request is still failing on clang-format. It seems like commit https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/291/commits/2e024a688a2c4ac9cfd475e3a034cf9d1e540f52 added some files to the platformio folder?

**Comment by brentru** [comment]
@afp316 Are you still interested in working on this issue?

**Comment by afp316** [comment]
Hey Brent, I kind of got sidetracked by other projects. I plan to finish it
up still.

**Comment by brentru** [comment]
@afp316 Are you still interested in working on this issue?

**Comment by afp316** [comment]
Hey Brent.  I kind of lost track on this one, I probably won't be finishing

**Comment by brentru** [comment]
No problem, @tyeth  is finishing it within https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/363

**Comment by tyeth** [comment]
Thanks @afp316 for your hard work! It wont be wasted, hopefully you get to reap the benefits too soon :)

**Comment by afp316** [comment]
I appreciate you snagging that! You're time won't go to waste. The driver
stuff isn't too mind boggling but honestly I couldn't figure how to do the
clang formatting and lint... I'm kind of a newb.

**Comment by tyeth** [comment]
Hey it threw me a bit too, vscode wasn't getting it 100% with the includes, and scanning seemed to be per file. In the end I cloned adafruits CI repo like the failing build did and ran the same clang / doxygen commands :)

**Pull request closed without merging**
