### PR TITLE
Update network port/cert support for local testing

### PR DESCRIPTION
**Pull request by tyeth**
Adds support for local dev machine testing, by allowing esp32 to specify port, and also disable mqtt security checking if not staging/production url

### CODE REVIEW

**Comment by tyeth** [comment]
Hey @brentru can you give this one a review please.
Will allow me to do end to end testing locally

**Review by brentru — CHANGES_REQUESTED** [review]
Looks like it addresses the cert issue, one question

**Comment by tyeth** [comment]
We default it to 8883 but it is also possible to override via Json, which
is what I need to do for the local testing on esp³², although the cert
insecure should allow local 8883 to work (if ssl setup)

**Comment by brentru** [comment]
>  We default it to 8883 

Where do we do this?

**Comment by tyeth** [comment]
> > We default it to 8883
> 
> Where do we do this?

https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/f51d4ac2e8baa8424717ce2e3a724b7bb5b40289/src/provisioning/ConfigJson.cpp#L49

**Review by brentru — APPROVED** [review]

**Pull request merged**
