### PR TITLE
Add SHT20

### PR DESCRIPTION
**Pull request by tyeth**
This is untested, awaiting feedback on https://github.com/adafruit/Wippersnapper_Components/pull/97

### CODE REVIEW

**Comment by brentru** [comment]
Hey @tyeth - @lorennorman  added a new feature that we're going to document in a bit, this is the perfect PR to test on.

We've added a new field (`"published":true`) to WipperSnapper component definitions [that have been added and released with a new firmware version of WipperSnapper](https://github.com/adafruit/Wippersnapper_Components/commit/fdb8e02b51c2cf99fac6d192fd38dfc3e6b554aa).

To test, once the component def. is pulled in...

In components, check the "show dev" box 
IO_-_Device__Adafruit_ESP32-S2_Feather

then, find the SHT20 component for testing
image

Test it out and post a screenshot here!

**Comment by tyeth** [comment]
Hey this is brilliant, unfortunately I haven't got the SHT20, could try tomorrow with the VL53L0X if that works with the preview components?

**Comment by brentru** [comment]
@tyeth  Did you get a SHT20 in for testing?

**Comment by tyeth** [comment]
no @brentru sorry, they were all out of stock or expensive locally so ordered from China, couple of weeks before I can test. I can stick it back to draft if preferred

**Comment by brentru** [comment]
Sure - let's mark this as a draft until ready!

**Comment by brentru** [comment]
@tyeth  checking in on the status of this PR

**Comment by tyeth** [comment]
my sensors are stuck in china, not sure if being reposted or got to buy more, stalled sorry.

**Comment by brentru** [comment]
no problem - it's almost CNY

**Comment by tyeth** [comment]
I'm culling this PR as the board works with Si7021 driver. New PR #409

**Pull request closed without merging**
