### PR TITLE
Add SHT41

### PR DESCRIPTION
**Pull request by tyeth**
Adds SHT41
https://www.adafruit.com/product/5776

Depends on https://github.com/adafruit/Wippersnapper_Components/pull/144

### CODE REVIEW

**Comment by brentru** [comment]
@tyeth  https://github.com/adafruit/Wippersnapper_Components/pull/144 has been merged and is online. When you have time, please test and add a screenshot to this PR.

**Comment by tyeth** [comment]
@brentru 
image

**Comment by brentru** [comment]
@tyeth  Try merging https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/474 into this branch to pass CI

**Comment by tyeth** [comment]
@brentru CI Passed and ready for review/merge, passed first time after 8266 fix (Was third of 3 rapid rebases)

**Review by brentru — APPROVED** [review]
This is an alias and LGTM

**Pull request merged**
