### PR TITLE
Initial ENS160 code

### PR DESCRIPTION
**Pull request by tyeth**
This adds support for the ENS160.

Blocked by https://github.com/adafruit/ENS160_driver/pull/5

Tested with two on the bus, Feather ESP32v2

image

### CODE REVIEW

**Comment by tyeth** [comment]
@brentru ready for a review. 
I've locally modified the platformio.ini to use my PR branch for the ens160 driver.
I've asked Carter to have a quick look at that PR, which will unblock this for CI + merge.

**Comment by brentru** [comment]
Will review once unblocked by arduino library

**Comment by tyeth** [comment]
@brentru unblocked

**Comment by tyeth** [comment]
Confused why this is failing but was running locally, I'll take a fresh look tomorrow

**Review by brentru — APPROVED** [review]
LGTM!

**Pull request merged**
