### PR TITLE
Add Adafruit ESP32 Feather V2

### PR DESCRIPTION
**Pull request by brentru**
Adds platform support for Adafruit ESP32 Feather V2
* Because a new release of https://github.com/espressif/arduino-esp32 was not cut yet, we're installing the arduino-esp32 bsp locally on the github runner, instead of from the BSP URL (https://github.com/brentru/ci-arduino). 
  * This step only executes on the ESP32 Feather V2, all other ESP32 platforms use the current Arduino ESP32 release
 
image

### CODE REVIEW

**Comment by ladyada** [comment]
can we tweak the adafruit ci to support manual installation as an option?

**Comment by brentru** [comment]
@ladyada  I could submit a separate PR over there! This repo uses the brentru adafruit ci fork though b/c of tinyusb build options.

**Comment by ladyada** [comment]
i'd really prefer we just keep to one arduino-ci script, or it will cause us confusion later :D

**Comment by brentru** [comment]
@ladyada  ok, no problem, lemmie work on combining them.

**Review by ladyada — APPROVED** [review]

**Pull request merged**
