### PR TITLE
Add SGP40

### PR DESCRIPTION
**Pull request by tyeth**
@brentru 
Takes 30minutes to start registering VOC_Index, expected but mental note to put a big warning in the wippersnapper learn guide page

CzuAbluwar
hSdjUh0YrF

### CODE REVIEW

**Comment by brentru** [comment]
@tyeth This is failing on CI

**Comment by tyeth** [comment]
@brentru everything will fail, Drazzy.com is returning connection refused as of a few hours ago. See https://github.com/SpenceKonde/ATTinyCore/issues/803

I wonder if we sponser them some CI help, there is mention of them being up for SSL setup assistance or CI help, but they don't know servers as well as embedded. We could fix their CI to host the board package on GH-pages. There's also the megaTinyCore repo. and the https://github.com/SpenceKonde/ReleaseScripts seems to contain the build logic at present

**Comment by tyeth** [comment]
@brentru ready for review

**Comment by brentru** [comment]
Merged https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/488, could you merge in this workflow and re-run?

**Review by brentru — APPROVED** [review]
@tyeth LGTM!

**Pull request merged**
