### PR TITLE
Add VCNL4040 / VCNL4020 Lux + Proximity sensor

### PR DESCRIPTION
**Pull request by tyeth**
https://www.adafruit.com/product/4161

### CODE REVIEW

**Comment by tyeth** [comment]
Worth noting @brentru there is a related issue in components repo https://github.com/adafruit/Wippersnapper_Components/pull/182

**Comment by brentru** [comment]
@tyeth  Looking at this, do you want me to review at this point in time?

**Comment by tyeth** [comment]
Screenshot 2024-01-11 212625

**Comment by tyeth** [comment]
> @tyeth Looking at this, do you want me to review at this point in time?

@brentru yes please

**Review by brentru — APPROVED** [review]

**Comment by brentru** [comment]
Approved, merging in!

**Pull request merged**
