### PR TITLE
feat: Add driver definition for Sensirion SHTC3

### PR DESCRIPTION
**Pull request by tyeth**
Uses existing arduino-sht driver from sensirion, same as SHT3x/40.
SHTC3 is available on address 0x70.
See also  https://github.com/adafruit/Wippersnapper_Components/issues/72

### CODE REVIEW

**Comment by tyeth** [comment]
No version bump included, I'm assuming you'll squeeze that in for v52 @brentru, but no worries if not.

**Review by brentru — APPROVED** [review]
LGTM, will merge when CI passes

**Comment by brentru** [comment]
@tyeth I'm going to include this PR and https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/340 in b52.

Could you bump the version number here: https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/main/src/Wippersnapper.h#L70

and here: https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/main/library.properties#L2

**Comment by tyeth** [comment]
Blessed, done. Thanks @brentru

**Comment by brentru** [comment]
@tyeth  Were you able to test this out on hardware?

**Comment by brentru** [comment]
Wow that's a busy QT Py. Going to re-run the flake job..

**Comment by brentru** [comment]
@tyeth Failing on https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/actions/runs/3191214395/jobs/5222965369#step:6:7

**Comment by brentru** [comment]
@tyeth  could you resolve the conflicts and we'll merge in?

**Comment by brentru** [comment]
@tyeth  Do you need this immediately? If not, it'll be published in the next release along with a few bugfixes.

**Pull request merged**
